package com.bedrock.core.ws.protocol;

import java.nio.charset.StandardCharsets;

/**
 * 🎓 BEDROCK TUTORIAL: Server Frame Serialization & Protocol Asymmetry
 *
 * <p>While the client is mandated by RFC 6455 §5.1 to mask every outgoing frame to prevent
 * transparent proxy cache poisoning, the server operates under opposite framing rules:</p>
 *
 * <h3>1. The Server Unmasked Invariant (RFC 6455 §5.1):</h3>
 * <p><i>"A server MUST NOT mask any frames that it sends to the client."</i></p>
 * <p>Consequently, every frame generated by {@link WebSocketFrameWriter}:</p>
 * <ol>
 *   <li>Has {@code MASK = 0} (Bit 7 of Byte 1 is always cleared).</li>
 *   <li>Does NOT contain a 4-byte masking key header.</li>
 *   <li>Transmits payload bytes directly without XOR permutation.</li>
 * </ol>
 * <p>
 * If a server were to send a masked frame, compliant RFC 6455 clients (such as Google Chrome,
 * Firefox, or {@code java.net.http.WebSocket}) would immediately terminate the connection
 * with close code 1002 (Protocol Error). Omitting server masking saves millions of CPU cycles
 * on high-throughput server nodes.
 * </p>
 *
 * <h3>2. Minimal Length Encoding Rules (RFC 6455 §5.2):</h3>
 * <p>RFC 6455 strictly requires using the minimum number of bytes to encode payload size:</p>
 * <ul>
 *   <li><b>Short Payloads (0 to 125 bytes)</b>:
 *       Encoded in a 2-byte header:
 *       {@code [Byte 0: 0x80 | Opcode, Byte 1: Length]}</li>
 *   <li><b>Medium Payloads (126 to 65,535 bytes)</b>:
 *       Encoded in a 4-byte header:
 *       {@code [Byte 0: 0x80 | Opcode, Byte 1: 126, Byte 2: Length MSB, Byte 3: Length LSB]}</li>
 *   <li><b>Large Payloads (&gt;= 65,536 bytes)</b>:
 *       Encoded in a 10-byte header:
 *       {@code [Byte 0: 0x80 | Opcode, Byte 1: 127, Bytes 2-9: 64-bit big-endian length]}</li>
 * </ul>
 *
 * <h3>3. Control Frame Constraints (RFC 6455 §5.5):</h3>
 * <p>Control frames (Ping 0x9, Pong 0xA, Close 0x8):</p>
 * <ul>
 *   <li>Must have {@code FIN = 1} (they cannot be fragmented across multiple frames).</li>
 *   <li>Must have payload length &lt;= 125 bytes.</li>
 *   <li>Close frames serialize a 2-byte unsigned big-endian status code followed by an optional UTF-8 reason string.</li>
 * </ul>
 */
public final class WebSocketFrameWriter {

    private static final byte[] EMPTY_BYTES = new byte[0];

    private WebSocketFrameWriter() {
        // Pure utility class
    }

    /**
     * Serializes an unmasked server UTF-8 text frame.
     *
     * @param text String content to send.
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createTextFrame(String text) {
        byte[] payload = text != null ? text.getBytes(StandardCharsets.UTF_8) : EMPTY_BYTES;
        return createFrame(WebSocketOpcode.TEXT, payload, true);
    }

    /**
     * Serializes an unmasked server binary frame.
     *
     * @param data Binary payload bytes.
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createBinaryFrame(byte[] data) {
        return createFrame(WebSocketOpcode.BINARY, data != null ? data : EMPTY_BYTES, true);
    }

    /**
     * Serializes an unmasked server Ping control frame.
     *
     * @param applicationData Optional heartbeat probe payload (must be &lt;= 125 bytes).
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createPingFrame(byte[] applicationData) {
        if (applicationData != null && applicationData.length > 125) {
            throw new IllegalArgumentException("Ping payload cannot exceed 125 bytes");
        }
        return createFrame(WebSocketOpcode.PING, applicationData != null ? applicationData : EMPTY_BYTES, true);
    }

    /**
     * Serializes an unmasked server Pong control frame echoing an incoming Ping.
     *
     * @param applicationData Heartbeat response payload echoing the Ping (must be &lt;= 125 bytes).
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createPongFrame(byte[] applicationData) {
        if (applicationData != null && applicationData.length > 125) {
            throw new IllegalArgumentException("Pong payload cannot exceed 125 bytes");
        }
        return createFrame(WebSocketOpcode.PONG, applicationData != null ? applicationData : EMPTY_BYTES, true);
    }

    /**
     * Serializes an unmasked server Close control frame with an RFC 6455 status code and optional reason.
     *
     * @param statusCode RFC 6455 status code (must not be wire-forbidden).
     * @param reason     Optional UTF-8 reason string.
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createCloseFrame(int statusCode, String reason) {
        WebSocketCloseStatus.validateSendCode(statusCode);
        byte[] reasonBytes = (reason != null && !reason.isEmpty()) ? reason.getBytes(StandardCharsets.UTF_8) : EMPTY_BYTES;
        if (2 + reasonBytes.length > 125) {
            throw new IllegalArgumentException("Close frame payload cannot exceed 125 bytes (2 status bytes + reason)");
        }

        byte[] payload = new byte[2 + reasonBytes.length];
        payload[0] = (byte) ((statusCode >>> 8) & 0xFF);
        payload[1] = (byte) (statusCode & 0xFF);
        if (reasonBytes.length > 0) {
            System.arraycopy(reasonBytes, 0, payload, 2, reasonBytes.length);
        }

        return createFrame(WebSocketOpcode.CLOSE, payload, true);
    }

    /**
     * Serializes an unmasked server frame (MASK = 0).
     *
     * @param opcode  The frame opcode.
     * @param payload Application payload bytes.
     * @param fin     True if final fragment.
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createFrame(WebSocketOpcode opcode, byte[] payload, boolean fin) {
        return encodeFrame(opcode, payload, fin, false, null);
    }

    /**
     * Serializes a masked frame (used primarily for unit testing and client simulation).
     *
     * @param opcode  The frame opcode.
     * @param payload Application payload bytes.
     * @param fin     True if final fragment.
     * @param maskKey Exactly 4 bytes of masking key.
     * @return Complete wire-formatted frame byte array.
     */
    public static byte[] createMaskedFrame(WebSocketOpcode opcode, byte[] payload, boolean fin, byte[] maskKey) {
        if (maskKey == null || maskKey.length != 4) {
            throw new IllegalArgumentException("Mask key must be exactly 4 bytes");
        }
        return encodeFrame(opcode, payload, fin, true, maskKey);
    }

    private static byte[] encodeFrame(WebSocketOpcode opcode, byte[] payload, boolean fin, boolean masked, byte[] maskKey) {
        if (payload == null) {
            payload = EMPTY_BYTES;
        }

        int payloadLen = payload.length;
        int headerLen;
        int lengthIndicator;

        if (payloadLen <= 125) {
            headerLen = 2;
            lengthIndicator = payloadLen;
        } else if (payloadLen <= 65535) {
            headerLen = 4;
            lengthIndicator = 126;
        } else {
            headerLen = 10;
            lengthIndicator = 127;
        }

        if (masked) {
            headerLen += 4; // 4-byte masking key
        }

        byte[] frame = new byte[headerLen + payloadLen];

        // Byte 0: FIN (bit 7) + Opcode (bits 3-0)
        frame[0] = (byte) ((fin ? 0x80 : 0x00) | (opcode.getCode() & 0x0F));

        // Byte 1: MASK bit (bit 7) + Payload length indicator (bits 6-0)
        frame[1] = (byte) ((masked ? 0x80 : 0x00) | (lengthIndicator & 0x7F));

        int offset = 2;

        // Extended payload length bytes
        if (lengthIndicator == 126) {
            frame[offset++] = (byte) ((payloadLen >>> 8) & 0xFF);
            frame[offset++] = (byte) (payloadLen & 0xFF);
        } else if (lengthIndicator == 127) {
            long len = payloadLen;
            frame[offset++] = (byte) ((len >>> 56) & 0xFF);
            frame[offset++] = (byte) ((len >>> 48) & 0xFF);
            frame[offset++] = (byte) ((len >>> 40) & 0xFF);
            frame[offset++] = (byte) ((len >>> 32) & 0xFF);
            frame[offset++] = (byte) ((len >>> 24) & 0xFF);
            frame[offset++] = (byte) ((len >>> 16) & 0xFF);
            frame[offset++] = (byte) ((len >>> 8) & 0xFF);
            frame[offset++] = (byte) (len & 0xFF);
        }

        // Masking key and payload
        if (masked) {
            System.arraycopy(maskKey, 0, frame, offset, 4);
            offset += 4;

            // Copy and XOR mask payload
            for (int i = 0; i < payloadLen; i++) {
                frame[offset + i] = (byte) (payload[i] ^ maskKey[i & 3]);
            }
        } else {
            // Unmasked: direct payload copy
            System.arraycopy(payload, 0, frame, offset, payloadLen);
        }

        return frame;
    }
}
